### ISSUE TITLE
Combine Custom Port and Custom Node Model

### ISSUE THREAD

**Issue by florianeichin** [Vonage/rxzu#67]
I managed to get a custom node model and a custom port model to work. What I wonder is how I combine both. So for instance how to add ports to the custom node model.

**Comment by DanielNetzeriAm** [comment]
Hi @florianeichin  do you mind sharing some code, the factories you created for each of the entities and anything that might help (the way you initialize the nodes, add ports, etc...)

**Comment by florianeichin** [comment]
Hi @DanielNetzeriAm basically I just try to add a port to this custom node example: https://github.com/Vonage/rxzu/tree/main/packages/storybook/stories/node/custom

**Comment by DanielNetzeriAm** [comment]
@florianeichin use the sample code from here https://github.com/Vonage/rxzu/blob/main/packages/angular/src/lib/defaults/factories/default-node.factory.ts
the storybook is incorrect, the factory must return the ViewContainerRef for the ports and that's why you get this error.

**Comment by florianeichin** [comment]
I just added a line of code, as your fix didn't completly fixed the issue on my side. Hope this is fine
