### ISSUE TITLE
Clone throws error

### ISSUE THREAD

**Issue by florianeichin** [Vonage/rxzu#74]
Hi, it seems, that cloning a link doesn't work as expected. Or do I have to prepare the link somehow before cloning?
here is my sample code:
```
const link = new DefaultLinkModel();
link.clone()
```

```
core.js:4442 ERROR TypeError: clone.setPoints is not a function
    at DefaultLinkModel.doClone (link.model.js:53)
    at DefaultLinkModel.clone (base.entity.js:50)
```

**Comment by DanielNetzeriAm** [comment]
a source port and a target port or a dangling point must be set for the link so it will be a valid link and clonable.

i'm actually working on a major change that will support `strict` mode for typescript in the entire libraries and storybook.
this will have better null/undefined detection to avoid this sort of issues.
it can be tracked here: https://github.com/Vonage/rxzu/tree/feat/strict-mode
