### ISSUE TITLE
Decouple the managers from the engine

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/rxzu#77]
Currently the manager instantiates the Factories and Mouse managers internally.
Having the ability to receive custom managers implementing the Manager's interfaces will allow us better flexibility, decoupling and testability.
Suggestion:
```
constructor(public managers: EngineManagers, public canvas$: ValueState<HTMLElement | null> = createValueState<HTMLElement | null>(null)) {
 // handle missing managers and set defaults if needed
}
```

**Comment by DanielNetzeriAm** [comment]
#96
