### ISSUE TITLE
Adding text to a node without creating a custom-node

### ISSUE THREAD

**Issue by robotab** [Vonage/rxzu#78]
As well as there is a method to create links between different nodes, add ports to create those links, establish coordinates, etc.

It would be nice if there was the possibility to add text to the nodes without having to create a custom-node, because in this way, you can organize everything in the same component while loading or creating the diagram. There is already a very similar method in the links, since there you can set text.

If the custom-node is used, it is very complicated to update the text of the node if it is extracted from a variable that can change.

**Comment by DanielNetzeriAm** [comment]
Hi @robotab, we are tirelessly working on refactoring some of the core functionalities when those are done, Themes are on the roadmap which will expose multiple types of custom nodes and capabilities.

**Comment by DanielNetzeriAm** [comment]
https://github.com/Vonage/rxzu/pull/96

**Comment by DanielNetzeriAm** [comment]
https://vonage.github.io/rxzu/?path=/story/themes-vonage-studio--vonage-studio
