### ISSUE TITLE
Dynamic Node Width breaks Port Coords

### ISSUE THREAD

**Issue by florianeichin** [Vonage/rxzu#82]
We set the dimension of our nodes dynamically. The HTML Element of the node is updating it's position correctly, but the `coords` of the ports doesn't. You can see this in the gif. in the blue circle, there are the html elements of the ports, that are moving, when the node grows. But the connections to the ports don't change. This is in the red circle.
![ezgif-5-3315ef1163af](https://user-images.githubusercontent.com/30117747/107956921-2d46d780-6fa0-11eb-9147-60d84fb55ac8.gif)

We update the width of the node like this:

```typescript
    this.model.dimensionChanges().subscribe((dimension) => {
      if (this.containerNode != null) {
        this.renderer.setStyle(this.containerNode.nativeElement, 'width', `${dimension.width}px`);
        this.renderer.setStyle(this.containerNode.nativeElement, 'height', `${dimension.height}px`);
      }
    });
```
I further inspected and I see, that the ports are correctly moving, when moving around the node, but not when setting the size

**Comment by DanielNetzeriAm** [comment]
#96 should resolve this.
