### ISSUE TITLE
How to test Service with factories?

### ISSUE THREAD

**Issue by florianeichin** [Vonage/rxzu#92]
Hi,
we have a service, that deals with all the graph actions.

we also have the registerFactories() method there. As in the examples this looks more or less like this:

```
registerFactories(): void {
    this._diagramEngine.registerDefaultFactories();
    this._diagramEngine.getFactoriesManager().registerFactory({
      type: 'nodeFactories',
      factory: new CustomFactory(this._resolver, this.renderer) as AbstractAngularFactory,
    });
```

The test looks like this. 
```
  beforeAll(() => {
    TestBed.configureTestingModule({
      providers: [
        DiagramEngine,
        ComponentFactoryResolver,
        OutputFormatEditorService,
      ]
    });

    service = TestBed.inject(OutputFormatEditorService);
    const factory = TestBed.inject(RendererFactory2);
    // service = new OutputFormatEditorService(engine, resolver);
    service.renderer = factory.createRenderer(null, null);
    service.registerFactories();
  })
```
When running the application normally in browser, everything works fine. But in test case, the result of `console.log(this._diagramEngine.getFactoriesManager()['nodeFactories'])` is always just `Map{}`

I think that this is because of `_renderer` or `_resolver`, but I have no idea how to overcome this. Are we doin things wrong on that side?

**Comment by florianeichin** [comment]
I see, this could relate to #87 , right?

**Comment by DanielNetzeriAm** [comment]
@florianeichin  indeed, closed.
